### ISSUE TITLE
Using the cookie_cover in combination with Blade?

### ISSUE THREAD

**Issue by geertjanknapen1** [dryven/cookie-byte#33]
We ported a legacy Laravel project to Statamic (quite a big project, can't do a re-write of the frontend). 

I can use `@antlers @endantlers` but if I use a Cookie Cover in that way, all the content within it breaks due to also using Blade to show images for example.
So I used `{!! Statamic::tag('cookie_modal') !!}` which works like a charm, but how do I use the CookieCover tag with blade?
I can do `{!! Statamig::tag('cookie_cover:my-handle') !!}` but I have no way to "close" the cookie_cover tag..

**Comment by dryven-daniel** [comment]
Hi @geertjanknapen1, 
I am not really familiar with blade and how it can be used in Statamic tbvh, but this seems to be a Statamic explaining exactly what you need, right? https://github.com/statamic/ideas/issues/802

You might be able to sort this out by simply creating a new partial and a slightly modified version of this code (well, with blade syntax) :

```{{ if enabled }}
<div class="ddm ddmcc" data-handle="{{ handle }}" data-categories="{{ categories }}" style="display:none;opacity:0;{{ if bg_image }}background-image: url('{{ bg_image:url }}'){{ /if }}">
	<div class="ddmcc-wrapper">
		<div class="ddmcc-content">
			<h2>{{ title }}</h2>
			<p>{{ paragraph }}</p>
			<div class="ddmcc-buttons centered">
				<button class="ddmcc-button-accept ddm-button inverted">{{ button_accept }}</button>
			</div>
		</div>
	</div>
	{{ if slot }}
	<textarea data-html-snippet disabled hidden>
		{{ slot }}
	</textarea>
	{{ /if }}
</div>
{{ /if }}
```

The cookie byte js should be able to handle the rest, since it queries the DOM for cookie covers by searching for ".ddmcc".
