### ISSUE TITLE
static caching saves pages with cookies disabled

### ISSUE THREAD

**Issue by Oleafeon** [dryven/cookie-byte#8]
We have a website with a couple youtube videos in the header, we added the function to disable the videos when one of the categories is not selected.
The website has static page caching enabled and after a couple of days the videos won't play anymore. When i look in the config i see that the categories are gone, but after deleting the cache they return and the videos play again.

is there a way to fix this?

**Comment by dryven-dano** [comment]
Hey Olivia!

How did you implement the function to block the videos from playing? Have you used the tag {{ cookie_consent }} or did you use the functions from JavaScript? When static page caching is enabled it could be, that it saves the state of the cookies being disabled and therefore not showing the content that should be loaded when cookies are enabled.

I'd be glad to assist you further on solving the issue when you provide me more information.

Cheers,
Dano.

**Comment by Oleafeon** [comment]
We used {{ if { cookie_consent has="marketing_cookies" } }} so yeah we used the tag

**Comment by dryven-dano** [comment]
Hey @Oleafeon!

Sorry for the late reply, there has been a lot going on lately. It seems like the page was statically cached. The thing is, the {{ cookie_consent }} tag is not compatible with static caching, as there are only static html files served to the client which won't correspond to their actual cookie byte settings. You could either add a code snippet to the cookie category which will add the YouTube video as soon as the cookies have been accepted or use the cookie cover with is now fully compatible with static caching since v1.1.1.

I hope this helps. If not, open the issue again and I'm glad to help you.

Cheers,
Dano.
